import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { buildPageMetadata } from '@/lib/seo'
import { EditableSiteShell } from '@/editable/shell/EditableSiteShell'
import { EditableLocalLoginForm } from '@/editable/components/EditableLocalAuthForms'
import { pagesContent } from '@/editable/content/pages.content'
export async function generateMetadata(): Promise<Metadata> { return buildPageMetadata({ path:'/login', title:'Login', description:pagesContent.auth.login.metadataDescription }) }
export default function LoginPage(){return <EditableSiteShell><main className="min-h-screen bg-[var(--slot4-panel-bg)] text-[var(--slot4-page-text)]"><section className="mx-auto grid min-h-[calc(100vh-76px)] max-w-[var(--editable-container)] items-stretch lg:grid-cols-[1.05fr_.95fr]"><div className="flex border-b border-[var(--editable-border)] p-6 sm:p-10 lg:border-b-0 lg:border-r lg:p-16"><div className="my-auto max-w-xl"><p className="text-[10px] font-bold uppercase tracking-[.22em]">Member access</p><h1 className="editable-display mt-7 text-5xl font-semibold leading-[.9] tracking-[-.065em] sm:text-7xl">Return to your saved threads.</h1><p className="mt-7 text-base leading-8 text-[var(--slot4-muted-text)]">Sign in to submit a useful resource and keep your contributions close at hand.</p><p className="mt-14 text-[10px] font-bold uppercase tracking-[.18em] text-[var(--slot4-muted-text)]">A considered index, built slowly.</p></div></div><div className="flex p-6 sm:p-10 lg:p-16"><div className="my-auto w-full max-w-md"><p className="text-[10px] font-bold uppercase tracking-[.22em]">Sign in</p><h2 className="editable-display mt-4 text-3xl font-semibold tracking-[-.05em]">Welcome back.</h2><EditableLocalLoginForm /><p className="mt-8 border-t border-[var(--editable-border)] pt-5 text-sm text-[var(--slot4-muted-text)]">New to the collection? <Link href="/signup" className="font-bold text-black underline underline-offset-4">Create an account <ArrowRight className="inline h-3.5 w-3.5"/></Link></p></div></div></section></main></EditableSiteShell>}
