import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'
import { buildPageMetadata } from '@/lib/seo'
import { EditableSiteShell } from '@/editable/shell/EditableSiteShell'
import { EditableLocalSignupForm } from '@/editable/components/EditableLocalAuthForms'
import { pagesContent } from '@/editable/content/pages.content'
export async function generateMetadata(): Promise<Metadata> { return buildPageMetadata({ path:'/signup', title:'Sign up', description:pagesContent.auth.signup.metadataDescription }) }
export default function SignupPage(){return <EditableSiteShell><main className="min-h-screen bg-[var(--slot4-page-bg)]"><section className="mx-auto grid min-h-[calc(100vh-76px)] max-w-[var(--editable-container)] lg:grid-cols-[.9fr_1.1fr]"><div className="order-2 flex border-t border-[var(--editable-border)] p-6 sm:p-10 lg:order-1 lg:border-r lg:border-t-0 lg:p-16"><div className="my-auto w-full max-w-md"><p className="text-[10px] font-bold uppercase tracking-[.22em]">Join the index</p><h1 className="editable-display mt-4 text-3xl font-semibold tracking-[-.05em]">Make room for good finds.</h1><EditableLocalSignupForm/><p className="mt-8 border-t border-[var(--editable-border)] pt-5 text-sm text-[var(--slot4-muted-text)]">Already a member? <Link href="/login" className="font-bold text-black underline underline-offset-4">Sign in <ArrowRight className="inline h-3.5 w-3.5"/></Link></p></div></div><div className="order-1 flex bg-black p-6 text-white sm:p-10 lg:order-2 lg:p-16"><div className="my-auto max-w-xl"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-white/55">Collections · Members</p><h2 className="editable-display mt-7 text-5xl font-semibold leading-[.9] tracking-[-.065em] sm:text-7xl">Keep the links that shape your work.</h2><div className="mt-10 space-y-4 text-sm leading-6 text-white/70">{['Submit resources worth returning to','Keep your contributions in one calm place','Help the catalogue become more useful'].map(item=><p key={item} className="flex gap-3"><Check className="h-4 w-4 shrink-0 text-white"/>{item}</p>)}</div></div></div></section></main></EditableSiteShell>}
