import Link from 'next/link'
import { ArrowRight, Bookmark, Check } from 'lucide-react'
import type { SitePost } from '@/lib/site-connector'
import type { HomeTimeSection } from '@/lib/task-data'
import type { TaskKey } from '@/lib/site-config'
import { CATEGORY_OPTIONS } from '@/lib/categories'
import { getEditableCategory, getEditableExcerpt, postHref } from '@/editable/cards/PostCards'
import { EditableReveal } from '@/editable/shell/EditableReveal'
type P={primaryTask:TaskKey;primaryRoute:string;posts:SitePost[];timeSections:HomeTimeSection[]}
const wrap='mx-auto max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-10'
function ResourceCard({post,href,index}:{post:SitePost;href:string;index:number}){return <EditableReveal index={index}><Link href={href} className="group block border-t border-[var(--editable-border)] py-5 transition hover:pl-2"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--slot4-muted-text)]">{String(index+1).padStart(2,'0')} · {getEditableCategory(post)}</p><h3 className="mt-2 text-2xl font-semibold leading-none tracking-[-.045em] group-hover:underline">{post.title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--slot4-muted-text)]">{getEditableExcerpt(post,120)}</p></Link></EditableReveal>}
export function EditableHomeHero({primaryRoute,posts}:P){const feature=posts[0];return <section className="border-b border-[var(--editable-border)]"><div className={`${wrap} grid gap-12 py-16 lg:grid-cols-[1.15fr_.85fr] lg:py-28`}><EditableReveal><p className="text-[10px] font-bold uppercase tracking-[.24em]">Collections · Members</p><h1 className="editable-display mt-7 max-w-4xl text-5xl font-semibold leading-[.9] tracking-[-.07em] sm:text-7xl lg:text-8xl">The good stuff, kept close.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--slot4-muted-text)]">A public library of bookmarks, resources, and useful corners of the internet—chosen to be revisited.</p><div className="mt-9 flex flex-wrap gap-3"><Link href={primaryRoute} className="bg-black px-6 py-3 text-[10px] font-bold uppercase tracking-[.16em] text-white">Explore collections</Link><Link href="/about" className="border border-black px-6 py-3 text-[10px] font-bold uppercase tracking-[.16em]">How it works</Link></div></EditableReveal><EditableReveal index={1}><div className="border border-black bg-black p-6 text-white sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/55">From the index</p><Bookmark className="mt-16 h-8 w-8"/>{feature?<><p className="mt-8 text-[10px] font-bold uppercase tracking-[.18em] text-white/55">{getEditableCategory(feature)}</p><h2 className="editable-display mt-3 text-4xl font-semibold leading-[.93] tracking-[-.05em]">{feature.title}</h2><Link href={postHref('sbm',feature,primaryRoute)} className="mt-10 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em]">Open resource <ArrowRight className="h-4 w-4"/></Link></>:null}</div></EditableReveal></div></section>}
export function EditableStoryRail({primaryRoute}:P){return <section className="overflow-hidden border-b border-[var(--editable-border)] bg-black py-5 text-white"><div className="flex min-w-max gap-10 px-5 text-xs font-bold uppercase tracking-[.18em] sm:px-8">{[...CATEGORY_OPTIONS,...CATEGORY_OPTIONS].map((category,index)=><Link key={`${category.slug}-${index}`} href={`${primaryRoute}?category=${category.slug}`} className="hover:text-white/50">{category.name} <span className="ml-10 text-white/40">✦</span></Link>)}</div></section>}
export function EditableMagazineSplit({primaryTask,primaryRoute,posts}:P){return <section className="border-b border-[var(--editable-border)]"><div className={`${wrap} py-16 lg:py-24`}><EditableReveal><p className="text-[10px] font-bold uppercase tracking-[.22em]">Why collect</p><div className="mt-5 grid gap-8 lg:grid-cols-2"><h2 className="editable-display text-4xl font-semibold leading-[.93] tracking-[-.055em] sm:text-5xl">A quieter way to find what matters.</h2><div className="space-y-4 text-sm leading-7 text-[var(--slot4-muted-text)]"><p className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-black"/>Save signal over noise, with a place for the links you mean to return to.</p><p className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-black"/>Browse by collection when you need a direction, not another endless feed.</p></div></div></EditableReveal><div className="mt-14 grid gap-x-10 md:grid-cols-2">{posts.slice(1,7).map((p,i)=><ResourceCard key={p.id||p.slug} post={p} index={i} href={postHref(primaryTask,p,primaryRoute)}/>)}</div></div></section>}
export function EditableTimeCollections({primaryTask,primaryRoute,posts,timeSections}:P){const resources=(timeSections.flatMap(x=>x.posts).length?timeSections.flatMap(x=>x.posts):posts).slice(0,12);return <section><div className={`${wrap} py-16 lg:py-24`}><EditableReveal><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.22em]">The shelves</p><h2 className="editable-display mt-3 text-4xl font-semibold tracking-[-.05em]">Recently gathered</h2></div><Link href={primaryRoute} className="text-xs font-bold uppercase tracking-[.16em] underline underline-offset-4">View all</Link></div></EditableReveal><div className="mt-10 grid border-l border-[var(--editable-border)] sm:grid-cols-2 lg:grid-cols-3">{resources.map((p,i)=><div className="border-b border-r border-[var(--editable-border)] px-5 py-6" key={p.id||p.slug}><ResourceCard post={p} index={i} href={postHref(primaryTask,p,primaryRoute)}/></div>)}</div></div></section>}
export function EditableHomeCta(){return <section className="border-t border-[var(--editable-border)] bg-[var(--slot4-panel-bg)]"><div className={`${wrap} py-20 text-center`}><EditableReveal><p className="text-[10px] font-bold uppercase tracking-[.22em]">Keep the thread</p><h2 className="editable-display mx-auto mt-5 max-w-3xl text-5xl font-semibold leading-[.9] tracking-[-.06em]">Have a resource worth passing on?</h2><p className="mx-auto mt-5 max-w-lg text-sm leading-7 text-[var(--slot4-muted-text)]">Submit a bookmark and help make the collection more useful for the next person.</p><Link href="/create" className="mt-8 inline-flex bg-black px-6 py-3 text-[10px] font-bold uppercase tracking-[.16em] text-white">Submit a resource</Link></EditableReveal></div></section>}
